# Generated by Django 3.2.5 on 2021-07-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sumary',
            new_name='summary',
        ),
    ]
