# Generated by Django 3.2.5 on 2021-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/no_image.png', upload_to='authors/'),
        ),
    ]
