# Generated by Django 3.2.5 on 2021-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210730_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-created', 'name'), 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='l_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Fulano', max_length=255, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(default='de Tal', max_length=255, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='author',
            name='citation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Citação'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/no_image.png', upload_to='authors/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/no_image.png', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
