# Generated by Django 3.2.5 on 2021-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210730_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
    ]
