# Generated by Django 3.2.5 on 2021-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210730_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edição'),
        ),
        migrations.AddField(
            model_name='book',
            name='publised_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publicação'),
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Volume'),
        ),
    ]
